create table person(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	full_name varchar(100) NOT NULL UNIQUE,
	year_of_birth int CHECK(year_of_birth > 1900)
);

create table book(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	person_id int REFERENCES person(id) ON DELETE SET NULL,
	title varchar(100) NOT NULL,
	author varchar(100) NOT NULL,
	year_of_issue int CHECK(year_of_issue > 1800)
)

INSERT INTO person(full_name, year_of_birth) VALUES('Таймаганбетов Айдос', 2002);
INSERT INTO person(full_name, year_of_birth) VALUES('Есенжолова Айгерим', 2006);
INSERT INTO person(full_name, year_of_birth) VALUES('Адилова Мадина', 2003);
INSERT INTO person(full_name, year_of_birth) VALUES('Курмаш Саят', 1992);


INSERT INTO book(person_id, title, author, year_of_issue) VALUES (2, 'Капитанская дочка', 'Александр Пушкин', 1825);
INSERT INTO book(person_id, title, author, year_of_issue) VALUES (1, 'Филосовия JAVA', 'Брюс Эккель', 2010);
INSERT INTO book(person_id, title, author, year_of_issue) VALUES (null, 'Бытие и время', 'Мартин Хайдеггер', 1927);
INSERT INTO book(person_id, title, author, year_of_issue) VALUES (null, 'Мастер и Маргарита', 'Михаил Булгаков', 1903);
INSERT INTO book(person_id, title, author, year_of_issue) VALUES (4, 'Три товарища', 'Эрих Мария Ремарк', 1885);
INSERT INTO book(person_id, title, author, year_of_issue) VALUES (1, 'Война и мир', 'Лев Толстой', 1999);
INSERT INTO book(person_id, title, author, year_of_issue) VALUES (null, 'На маяк', 'Вирджиния Вулф', 2015);
INSERT INTO book(person_id, title, author, year_of_issue) VALUES (2, 'Звук и ярость', 'Уильям Фолкнер', 2021);
INSERT INTO book(person_id, title, author, year_of_issue) VALUES (1, 'Цветы для Элджернона', 'Дэниел Киз', 2001);
INSERT INTO book(person_id, title, author, year_of_issue) VALUES (1, 'Над пропастью во ржи', 'Рэй Брэдбери', 1998);


select * from book ORDER BY id

SELECT book.title, book.author, book.year_of_issue FROM book JOIN person ON book.person_id = person.id WHERE person.id = 2

SELECT person.full_name FROM person RIGHT JOIN book ON book.person_id = person.id WHERE book.id = 4

UPDATE book set person_id = NULL where id = 3
